services:
  - type: web
    name: ev-charging-ai-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard.py --server.port $PORT
    pythonVersion: 3.10.14
